### ISSUE TITLE
Interface de jeu - Définir la taille de la zone de jeux

### ISSUE THREAD

**Issue by matthieu-brillaxis** [ecvdbdx1617/MultiSnake#22] opened 2016-11-17 12:48 UTC
Créer la zone de jeux qui accueil les serpents (taille customisable pour les partie privé ?)

**Comment by simon-milleto** [comment] 2016-11-17 15:13
Definition of done : create a canvas object which is the game area (1600x900)

**Comment by DavidBruant** [comment] 2016-11-17 15:16
The "Definition of done" is rather something like : "when the player opens the game, a canvas element representing the game area is displayed".
But fine. You can proceed

**Comment by DavidBruant** [comment] 2016-12-08 17:12
Dupe of #74

**Closed as completed by DavidBruant** 2016-12-08 17:12 UTC
Labels: Tableau de jeu
